version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "18"
    rust: "1.64"
    golang: "1.19"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

conda:
  environment: rtd-environment.yml