name: bagpipes

dependencies:
    - python
    - astropy
    - scipy
    - matplotlib
    - numpy==1.22.4
    - pybind11
    - h5py
    - pip:
      - corner
      - pymultinest
      - msgpack
      - pandas
      - spectres
