name: bagpipes

dependencies:
    - python
    - astropy
    - scipy
    - matplotlib>=2.2.2
    - numpy>=1.14.2
    - pybind11
    - pip:
      - corner
      - pymultinest
      - msgpack
      - deepdish
      - pandas<=1.1.5
