name: bagpipes

dependencies:
    - python=2.7
    - astropy=2.0.5
    - scipy
    - matplotlib>=2.2.2
    - numpy>=1.14.2
    - pip:
      - corner
      - pymultinest
      - dynesty
      - msgpack
      - deepdish
      - pandas

