name: bagpipes

dependencies:
    - python
    - astropy
    - scipy
    - matplotlib
    - numpy<1.23.0
    - pybind11
    - h5py
    - pip:
      - corner
      - pymultinest
      - msgpack
      - pandas
      - spectres
